resources/recipes/configure.rb

Call configure_keys for nmsp, between :add and :register

Add call to configure nmsp keys

---

packaging/rpm/cookbook-rb-manager.spec
resources/libraries/get_sensors_all_info.rb
resources/libraries/get_sensors_info.rb

* manager picks only its own sensors
* useless boolean clean
* Added new sensors to whitelist copying from proxy
* spec update

Feature/13838 sensors info proxy and manager (#76)

---

resources/recipes/configure.rb

added kafka_hosts line in configuration of pmacct

added kafka hosts configuration to pmacct

---

packaging/rpm/cookbook-rb-manager.spec

* Add rb-arubacentral service and cookbook configuration

Release 1.6.7

---

resources/recipes/configure_journald.rb
resources/templates/default/systemd-journald_journald.conf.erb

PR 102 - Add positiblity to custom set Storage value of journald configuration

---

packaging/rpm/cookbook-rb-manager.spec

* Add journalctd configuration

Release 1.6.8

---

resources/metadata.rb

New in this release:
- Added redborder-cep configuration in `resources/recipes/configure.rb`

Release 1.7.1

---

resources/metadata.rb

New in this release:
- All flow sensors (including the ones in the proxy) are passed to the sflow pipeline

Release 1.7.2

---

CHANGELOG.md

Release 1.7.3

---

resources/recipes/configure.rb

pass the sync ipaddress to the minio cookbook to register the service

add ipaddress sync for minio

---

CHANGELOG.md
resources/metadata.rb

Release 1.7.4

---

.github/workflows/rpm.yml
CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

- [10301b6] Add parition id for druid realtime by @malvads 
- [17142d4] Use zookeeper.service instead of hardcoded localhost by @malvads

Release 1.7.6

---

resources/libraries/get_pipelines.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

Imported the logstash template from centos6; so when a sensor does not exist, the pipeline does not exist.

imported logstash template from centos6

---

CHANGELOG.md
resources/libraries/get_pipelines.rb
resources/metadata.rb

- [ae88eb5] fix_logstash_crash by @nilsver

Release 1.7.8

---

resources/recipes/prepare_system.rb

Reverts redBorder/cookbook-rb-manager#132

Revert "Bugfix/17236 logstash enabled without pipelines"

---

.github/workflows/rpm.yml
CHANGELOG.md
Makefile
resources/metadata.rb
resources/recipes/prepare_system.rb

By  @malvads 
- [1c900b6] Update prepare_system.rb
- [f9d986c] Update memory_services.rb
- [546e802] rename to excluded_memory_services

Release 1.7.9

---

resources/recipes/configure.rb

If there are no pipelines, logstash will stop running

Stop logstash when there are no pipelines

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

- [f66e148] added conditional check on pipelines by @nilsver

Release 1.7.10

---

.github/workflows/rpm.yml
CHANGELOG.md
resources/metadata.rb

Release 1.9.2

---

resources/recipes/configure.rb

Check if pipelines are there, and run logstash based on that condition

fix check if pipelines are active

---

resources/recipes/configure.rb

* This PR is for passing the memcache hosts to the webui

Add memcached hosts to the webui

---

CHANGELOG.md
resources/metadata.rb

Feature/#17820 add intrusion pipeline

Release 2.3.0

---

CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb

- Pablo Pérez
- [b0a6896] Added default value of node variable sso_enabled

Release 2.5.0

---

CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb

Added nodes to druid.cache.hosts with memcached port. For druid to improve caching performance.

Release 2.5.2

---

resources/recipes/prepare_system.rb

Related PRs:
- https://github.com/redBorder/cookbook-webui/pull/57

Avoid using .node references in nginx

---

CHANGELOG.md
resources/metadata.rb

- Fix path to avoid cron_d action delete by @jnavarrorb in #192

Release 2.9.1

---

resources/recipes/configure.rb

Related PRs:
- https://github.com/redBorder/redborder-manager/pull/183
- https://github.com/redBorder/cookbook-minio/pull/26
- https://github.com/redBorder/cookbook-rb-manager/pull/212

Feature/add mc tool (mcli)

---

resources/recipes/configure.rb

* Do same check for logstatter and logstash so both services are enabled at the same time.

Make same check for logstatter and logstash to configure

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

@malvads 
- [7930ce6] Make same check for logstatter and logstash to configure

Release 4.4.6

---

resources/recipes/configure.rb

* If databag has the keys, always create the files

Always create s3cfg_initial on all nodes

---

CHANGELOG.md
resources/libraries/get_pipelines.rb
resources/metadata.rb

- Always enable vault logstash pipeline

Release 4.7.0

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

By @davidredborder:
- [2971573] load s3_host from s3_secrets databag

Release 4.7.2 

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

- Fix to upload elasticache data bag by @nilsver in #262

Release 4.7.4

---

resources/recipes/configure.rb

* Use CPU num for compute proc threads in Druid

Use CPU num

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

- Ensure S3 Configuration Applies Correctly When Nginx is Enabled and S3 is Disabled (add_s3) by @nilsver in #273

Release 4.8.3

---

CHANGELOG.md
resources/metadata.rb

Fix get_sensors_info getting wrong the sensor type by @nilsver in #281

Release 4.10.1

---

CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb

* Fix organization megabytes limit issue with http2k by @jnavarrorb in #292

Release 5.0.2

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

* Dont delete psql or s3 if databag of external services by @rgomezborder in #294

Release 5.0.3

---

resources/libraries/get_pipelines.rb
resources/libraries/get_sensors_info.rb
resources/recipes/configure.rb

* Add support for intrusioncp sensor (logstash & http2k)

New sensor type 'intrusioncp-sensor' (intrusion proxy sensor)

---

CHANGELOG.md
resources/libraries/get_pipelines.rb
resources/libraries/get_sensors_info.rb
resources/metadata.rb
resources/recipes/configure.rb

* Add intrusion proxy sensor by @malvads in #291

Release 5.1.0

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

[Feature #21708](https://redmine.redborder.lan/issues/21708): [redborder-webui] Remove darklist system as is replaced by TI policies in #305

Release 5.3.2

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

Fix cdomain in s3cfg_initial file

Release 5.4.0

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb
resources/templates/default/rsa_cert.pem.erb

Add RSA key templates for SSH configuration

Release 5.4.1

---

CHANGELOG.md
resources/metadata.rb

Syslog port (514) is open tcp/udp for everybody in public and it should not by @pperezredborder in #303

Release 5.4.2

---

CHANGELOG.md
resources/metadata.rb

prepary_system taking too long as we yum cache clean metadata all the time by @nilsver in #312

Release 5.4.4

---

CHANGELOG.md
resources/metadata.rb

Release 5.4.5

---

CHANGELOG.md
resources/libraries/get_indexer_tasks.rb
resources/metadata.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

Task #320 made by @rgomezborder

Release 5.4.7

---

CHANGELOG.md
resources/libraries/get_indexer_tasks.rb
resources/libraries/get_sensors_info.rb
resources/metadata.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

By @nilsver:
- only query scanner sensors from managers [f6783ad5c93638f0a5a22d25f2f21ec4452034a3]

Release 5.6.1

---

CHANGELOG.md
resources/metadata.rb
resources/recipes/configure.rb

[Create s3 malware bucket in rb_configure_leader.sh](https://redmine.redborder.lan/issues/22453)
------------------------------------------------------
Task by pperez@redborder.com
Authored by dcastro@redborder.com

Release 5.11.1

---

CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb

Change port to default port (3000) by @pperezredborder in #359

Release 5.13.1

---

CHANGELOG.md
resources/attributes/default.rb
resources/libraries/get_cluster_info.rb
resources/metadata.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

Change Aerospike IP address from management to sync by @manegron in #367

Release 5.15.2

---

CHANGELOG.md
resources/libraries/get_sensors_info.rb
resources/metadata.rb
resources/recipes/configure.rb
resources/recipes/prepare_system.rb

Activate malware module and check that all works by @pperezredborder in #363

Release 5.16.0

---

CHANGELOG.md
resources/attributes/default.rb
resources/metadata.rb

feature/#22789_bring_back_virustotal_analysis by @pperezredborder #379

Release 5.17.2
